name: e2e tests for flannel

on: [push, pull_request]

jobs:
  e2e-test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run tests
      id: testing
      continue-on-error: true
      run: git fetch --all --tags && make test 2>&1 > errors.txt
    - name: Show additional logs
      if: steps.testing.outcome != 'success'
      run: |
            cat errors.txt
            exit 1
